services:
  spark-master:
    build:
      context: .
      dockerfile: spark-cluster.Dockerfile
    container_name: spark-master
    environment:
      - SPARK_WORKLOAD=master
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./workspace:/opt/workspace

  spark-worker-1:
    build:
      context: .
      dockerfile: spark-cluster.Dockerfile
    container_name: spark-worker-1
    environment:
      - SPARK_WORKLOAD=worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "18081:18081"
    volumes:
      - ./workspace:/opt/workspace

  spark-worker-2:
    build:
      context: .
      dockerfile: spark-cluster.Dockerfile
    container_name: spark-worker-2
    environment:
      - SPARK_WORKLOAD=worker
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
      - "18082:18081"
    volumes:
      - ./workspace:/opt/workspace
